[build]
  functions = "service"

[[redirects]]
  from = "/people*"
  to = "/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  POLICY_INSTANCE_NAME = "Policy instance name"
  TENANT_ID = "Aserto tenant ID"
  AUTHORIZER_API_KEY = "Aserto authorizer API key"
  DIRECTORY_API_KEY = "Aserto directory read/write API key"
  REACT_APP_NETLIFY = "Netlify flag must be set to NETLIFY"

[context.production]
  publish = "build/"
  command = "yarn build"
